// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: feeds.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createFeed = `-- name: CreateFeed :one
INSERT INTO feeds (id, created_at, updated_at, name, url, user_id)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
RETURNING id, created_at, updated_at, name, url, user_id
`

type CreateFeedParams struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Name      string
	Url       string
	UserID    uuid.UUID
}

func (q *Queries) CreateFeed(ctx context.Context, arg CreateFeedParams) (Feed, error) {
	row := q.db.QueryRowContext(ctx, createFeed,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Name,
		arg.Url,
		arg.UserID,
	)
	var i Feed
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.Url,
		&i.UserID,
	)
	return i, err
}

const showFeeds = `-- name: ShowFeeds :many
SELECT feeds.name, feeds.url, users.name AS feed_creator
FROM feeds
INNER JOIN users
ON feeds.user_id = users.id
`

type ShowFeedsRow struct {
	Name        string
	Url         string
	FeedCreator string
}

func (q *Queries) ShowFeeds(ctx context.Context) ([]ShowFeedsRow, error) {
	rows, err := q.db.QueryContext(ctx, showFeeds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ShowFeedsRow
	for rows.Next() {
		var i ShowFeedsRow
		if err := rows.Scan(&i.Name, &i.Url, &i.FeedCreator); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
